export const seats: SeatListItem[] = [
  { id: 'A1', booked: true },
  { id: 'A2', unavailable: true },
  { id: 'A3', booked: true },
  { id: 'A4' },
  { id: 'A5' },
  {},
  {},
  { id: 'A6' },
  { id: 'A7' },
  { id: 'A8' },
  { id: 'A9' },
  { id: 'A10' },
  { id: 'B1' },
  { id: 'B2', booked: true },
  { id: 'B3' },
  { id: 'B4', booked: true },
  { id: 'B5' },
  {},
  {},
  { id: 'B6', booked: true },
  { id: 'B7', booked: true },
  { id: 'B8' },
  { id: 'B9' },
  { id: 'B10' },
  { id: 'C1', booked: true },
  { id: 'C2', booked: true },
  { id: 'C3' },
  { id: 'C4' },
  { id: 'C5' },
  {},
  {},
  { id: 'C6' },
  { id: 'C7' },
  { id: 'C8' },
  { id: 'C9' },
  { id: 'C10' },
  { id: 'D1' },
  { id: 'D2' },
  { id: 'D3' },
  { id: 'D4' },
  { id: 'D5' },
  {},
  {},
  { id: 'D6', booked: true },
  { id: 'D7', unavailable: true },
  { id: 'D8', booked: true },
  { id: 'D9', unavailable: true, booked: true },
  { id: 'D10', booked: true },
  { id: 'E1' },
  { id: 'E2', unavailable: true },
  { id: 'E3' },
  { id: 'E4' },
  { id: 'E5', booked: true },
  {},
  {},
  { id: 'E6' },
  { id: 'E7' },
  { id: 'E8' },
  { id: 'E9' },
  { id: 'E10' },
  { id: 'F1' },
  { id: 'F2' },
  { id: 'F3' },
  { id: 'F4', booked: true },
  { id: 'F5', booked: true },
  {},
  {},
  { id: 'F6' },
  { id: 'F7' },
  { id: 'F8' },
  { id: 'F9', booked: true },
  { id: 'F10', booked: true },
];
